name: Auto Merge Main to Test

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{secrets.ACTIONS_PAT}}

      - name: Configure Git
        run: |
          git config --global user.name '2srivani'
          git config --global user.email 'arumullasrivani1234@gmail.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into test
        run: |
          git checkout test
          git merge main -X theirs --allow-unrelated-histories
          git push origin test